[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/dscr-loans"
  to = "/dscr-loans/index.html"
  status = 200

[[redirects]]
  from = "/quiz"
  to = "/quiz.html"
  status = 200

[[redirects]]
  from = "/review"
  to = "/review.html"
  status = 200

[[redirects]]
  from = "/dscr-calculator"
  to = "/dscr-calculator.html"
  status = 200
